symbols:
- code: TXFL6
  exchange: FUT
- code: TXFF6
  exchange: FUT
- code: TXFI6
  exchange: FUT
- code: TXFC6
  exchange: FUT
- code: TXFB6
  exchange: FUT
- code: TXFA6
  exchange: FUT
- code: TXFR1
  exchange: FUT
- code: TXFR2
  exchange: FUT
- code: MXFC6
  exchange: FUT
- code: MXFA6
  exchange: FUT
- code: MXFL6
  exchange: FUT
- code: MXFF6
  exchange: FUT
- code: MXFI6
  exchange: FUT
- code: MXFB6
  exchange: FUT
- code: MXFR1
  exchange: FUT
- code: MXFR2
  exchange: FUT
- code: ZEFF6
  exchange: FUT
- code: ZEFB6
  exchange: FUT
- code: ZEFA6
  exchange: FUT
- code: ZEFI6
  exchange: FUT
- code: ZEFC6
  exchange: FUT
- code: ZEFL6
  exchange: FUT
- code: ZEFR1
  exchange: FUT
- code: ZEFR2
  exchange: FUT
