symbols:
- code: '1101'
  name: "\u53F0\u6CE5"
  exchange: TSE
  product_type: stock
- code: '1102'
  name: "\u4E9E\u6CE5"
  exchange: TSE
  product_type: stock
- code: '1216'
  name: "\u7D71\u4E00"
  exchange: TSE
  product_type: stock
- code: '1301'
  name: "\u53F0\u5851"
  exchange: TSE
  product_type: stock
- code: '1303'
  name: "\u5357\u4E9E"
  exchange: TSE
  product_type: stock
- code: '1326'
  name: "\u53F0\u5316"
  exchange: TSE
  product_type: stock
- code: '1402'
  name: "\u9060\u6771\u65B0"
  exchange: TSE
  product_type: stock
- code: '2002'
  name: "\u4E2D\u92FC"
  exchange: TSE
  product_type: stock
- code: '2201'
  name: "\u88D5\u9686"
  exchange: TSE
  product_type: stock
- code: '2207'
  name: "\u548C\u6CF0\u8ECA"
  exchange: TSE
  product_type: stock
- code: '2301'
  name: "\u5149\u5BF6\u79D1"
  exchange: TSE
  product_type: stock
- code: '2303'
  name: "\u806F\u96FB"
  exchange: TSE
  product_type: stock
- code: '2308'
  name: "\u53F0\u9054\u96FB"
  exchange: TSE
  product_type: stock
- code: '2317'
  name: "\u9D3B\u6D77"
  exchange: TSE
  product_type: stock
- code: '2327'
  name: "\u570B\u5DE8*"
  exchange: TSE
  product_type: stock
- code: '2330'
  name: "\u53F0\u7A4D\u96FB"
  exchange: TSE
  product_type: stock
- code: '2345'
  name: "\u667A\u90A6"
  exchange: TSE
  product_type: stock
- code: '2354'
  name: "\u9D3B\u6E96"
  exchange: TSE
  product_type: stock
- code: '2357'
  name: "\u83EF\u78A9"
  exchange: TSE
  product_type: stock
- code: '2379'
  name: "\u745E\u6631"
  exchange: TSE
  product_type: stock
- code: '2382'
  name: "\u5EE3\u9054"
  exchange: TSE
  product_type: stock
- code: '2395'
  name: "\u7814\u83EF"
  exchange: TSE
  product_type: stock
- code: '2408'
  name: "\u5357\u4E9E\u79D1"
  exchange: TSE
  product_type: stock
- code: '2409'
  name: "\u53CB\u9054"
  exchange: TSE
  product_type: stock
- code: '2412'
  name: "\u4E2D\u83EF\u96FB"
  exchange: TSE
  product_type: stock
- code: '2454'
  name: "\u806F\u767C\u79D1"
  exchange: TSE
  product_type: stock
- code: '2474'
  name: "\u53EF\u6210"
  exchange: TSE
  product_type: stock
- code: '2603'
  name: "\u9577\u69AE"
  exchange: TSE
  product_type: stock
- code: '2609'
  name: "\u967D\u660E"
  exchange: TSE
  product_type: stock
- code: '2615'
  name: "\u842C\u6D77"
  exchange: TSE
  product_type: stock
- code: '2801'
  name: "\u5F70\u9280"
  exchange: TSE
  product_type: stock
- code: '2881'
  name: "\u5BCC\u90A6\u91D1"
  exchange: TSE
  product_type: stock
- code: '2882'
  name: "\u570B\u6CF0\u91D1"
  exchange: TSE
  product_type: stock
- code: '2883'
  name: "\u51F1\u57FA\u91D1"
  exchange: TSE
  product_type: stock
- code: '2884'
  name: "\u7389\u5C71\u91D1"
  exchange: TSE
  product_type: stock
- code: '2885'
  name: "\u5143\u5927\u91D1"
  exchange: TSE
  product_type: stock
- code: '2886'
  name: "\u5146\u8C50\u91D1"
  exchange: TSE
  product_type: stock
- code: '2887'
  name: "\u53F0\u65B0\u65B0\u5149\u91D1"
  exchange: TSE
  product_type: stock
- code: '2890'
  name: "\u6C38\u8C50\u91D1"
  exchange: TSE
  product_type: stock
- code: '2891'
  name: "\u4E2D\u4FE1\u91D1"
  exchange: TSE
  product_type: stock
- code: '2892'
  name: "\u7B2C\u4E00\u91D1"
  exchange: TSE
  product_type: stock
- code: '2912'
  name: "\u7D71\u4E00\u8D85"
  exchange: TSE
  product_type: stock
- code: '3008'
  name: "\u5927\u7ACB\u5149"
  exchange: TSE
  product_type: stock
- code: '3034'
  name: "\u806F\u8A60"
  exchange: TSE
  product_type: stock
- code: '3045'
  name: "\u53F0\u7063\u5927"
  exchange: TSE
  product_type: stock
- code: '3711'
  name: "\u65E5\u6708\u5149\u6295\u63A7"
  exchange: TSE
  product_type: stock
- code: '4904'
  name: "\u9060\u50B3"
  exchange: TSE
  product_type: stock
- code: '4938'
  name: "\u548C\u78A9"
  exchange: TSE
  product_type: stock
- code: '5871'
  name: "\u4E2D\u79DF-KY"
  exchange: TSE
  product_type: stock
- code: '5880'
  name: "\u5408\u5EAB\u91D1"
  exchange: TSE
  product_type: stock
- code: TXFB6
  name: "\u81FA\u80A1\u671F\u8CA802"
  exchange: FUT
  product_type: future
  tags:
  - futures
  - front_month
  - txf
- code: TXFD6
  name: "\u81FA\u80A1\u671F\u8CA804"
  exchange: FUT
  product_type: future
  tags:
  - futures
  - far_month
  - txf
- code: MXFB6
  name: "\u5C0F\u578B\u81FA\u630702"
  exchange: FUT
  product_type: future
  tags:
  - futures
  - front_month
  - mxf
- code: MXFD6
  name: "\u5C0F\u578B\u81FA\u630704"
  exchange: FUT
  product_type: future
  tags:
  - futures
  - far_month
  - mxf
- code: TMFB6
  name: "\u5FAE\u578B\u81FA\u6307\u671F\u8CA802"
  exchange: FUT
  product_type: future
  tags:
  - futures
  - front_month
  - tmf
- code: TMFD6
  name: "\u5FAE\u578B\u81FA\u6307\u671F\u8CA804"
  exchange: FUT
  product_type: future
  tags:
  - futures
  - far_month
  - tmf
- code: TXO23000N6
  name: "\u81FA\u6307\u9078\u64C7\u6B0AF502\u670823000P"
  exchange: OPT
  product_type: option
  tags:
  - options
  - near_month
  - atm
  - txo
- code: TXO23400B6
  name: "\u81FA\u6307\u9078\u64C7\u6B0AF502\u670823400C"
  exchange: OPT
  product_type: option
  tags:
  - options
  - near_month
  - atm
  - txo
- code: TXO22900B6
  name: "\u81FA\u6307\u9078\u64C7\u6B0AF502\u670822900C"
  exchange: OPT
  product_type: option
  tags:
  - options
  - near_month
  - atm
  - txo
- code: TXO23300B6
  name: "\u81FA\u6307\u9078\u64C7\u6B0AF502\u670823300C"
  exchange: OPT
  product_type: option
  tags:
  - options
  - near_month
  - atm
  - txo
- code: TXO22500N6
  name: "\u81FA\u6307\u9078\u64C7\u6B0AF502\u670822500P"
  exchange: OPT
  product_type: option
  tags:
  - options
  - near_month
  - atm
  - txo
- code: TXO23100B6
  name: "\u81FA\u6307\u9078\u64C7\u6B0AF502\u670823100C"
  exchange: OPT
  product_type: option
  tags:
  - options
  - near_month
  - atm
  - txo
- code: TXO22700B6
  name: "\u81FA\u6307\u9078\u64C7\u6B0AF502\u670822700C"
  exchange: OPT
  product_type: option
  tags:
  - options
  - near_month
  - atm
  - txo
- code: TXO23000B6
  name: "\u81FA\u6307\u9078\u64C7\u6B0AF502\u670823000C"
  exchange: OPT
  product_type: option
  tags:
  - options
  - near_month
  - atm
  - txo
- code: TXO23200N6
  name: "\u81FA\u6307\u9078\u64C7\u6B0AF502\u670823200P"
  exchange: OPT
  product_type: option
  tags:
  - options
  - near_month
  - atm
  - txo
- code: TXO22600B6
  name: "\u81FA\u6307\u9078\u64C7\u6B0AF502\u670822600C"
  exchange: OPT
  product_type: option
  tags:
  - options
  - near_month
  - atm
  - txo
- code: TXO22700N6
  name: "\u81FA\u6307\u9078\u64C7\u6B0AF502\u670822700P"
  exchange: OPT
  product_type: option
  tags:
  - options
  - near_month
  - atm
  - txo
- code: TXO22800N6
  name: "\u81FA\u6307\u9078\u64C7\u6B0AF502\u670822800P"
  exchange: OPT
  product_type: option
  tags:
  - options
  - near_month
  - atm
  - txo
- code: TXO23200B6
  name: "\u81FA\u6307\u9078\u64C7\u6B0AF502\u670823200C"
  exchange: OPT
  product_type: option
  tags:
  - options
  - near_month
  - atm
  - txo
- code: TXO22400N6
  name: "\u81FA\u6307\u9078\u64C7\u6B0AF502\u670822400P"
  exchange: OPT
  product_type: option
  tags:
  - options
  - near_month
  - atm
  - txo
- code: TXO22800B6
  name: "\u81FA\u6307\u9078\u64C7\u6B0AF502\u670822800C"
  exchange: OPT
  product_type: option
  tags:
  - options
  - near_month
  - atm
  - txo
- code: TXO22900N6
  name: "\u81FA\u6307\u9078\u64C7\u6B0AF502\u670822900P"
  exchange: OPT
  product_type: option
  tags:
  - options
  - near_month
  - atm
  - txo
- code: TXO23300N6
  name: "\u81FA\u6307\u9078\u64C7\u6B0AF502\u670823300P"
  exchange: OPT
  product_type: option
  tags:
  - options
  - near_month
  - atm
  - txo
- code: TXO22500B6
  name: "\u81FA\u6307\u9078\u64C7\u6B0AF502\u670822500C"
  exchange: OPT
  product_type: option
  tags:
  - options
  - near_month
  - atm
  - txo
- code: TXO23100N6
  name: "\u81FA\u6307\u9078\u64C7\u6B0AF502\u670823100P"
  exchange: OPT
  product_type: option
  tags:
  - options
  - near_month
  - atm
  - txo
- code: TXO22400B6
  name: "\u81FA\u6307\u9078\u64C7\u6B0AF502\u670822400C"
  exchange: OPT
  product_type: option
  tags:
  - options
  - near_month
  - atm
  - txo
- code: TXO23400N6
  name: "\u81FA\u6307\u9078\u64C7\u6B0AF502\u670823400P"
  exchange: OPT
  product_type: option
  tags:
  - options
  - near_month
  - atm
  - txo
- code: TXO22600N6
  name: "\u81FA\u6307\u9078\u64C7\u6B0AF502\u670822600P"
  exchange: OPT
  product_type: option
  tags:
  - options
  - near_month
  - atm
  - txo
